// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizedJihad.Data;

#nullable disable

namespace OrganizedJihad.Data.Migrations
{
    [DbContext(typeof(GameDatabaseContext))]
    [Migration("20251022204812_InitialCreateWithAudit")]
    partial class InitialCreateWithAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("OrganizedJihad.Data.Models.ArenaBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("OurTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("RankAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("IsWin", "Timestamp");

                    b.ToTable("ArenaBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableReminders")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrencePattern")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReminderMinutesBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("IsCompleted");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestOpeningId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChestOpeningId");

                    b.HasIndex("ItemId");

                    b.ToTable("ChestDrops");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestOpening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChestType");

                    b.HasIndex("Timestamp");

                    b.ToTable("ChestOpenings");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("Type");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GrandArenaBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenseTeam")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentAttackTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpponentDefenseTeam")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("Timestamp");

                    b.ToTable("GrandArenaBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildWarBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenderTeam")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyGuildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FortificationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OurTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WarId");

                    b.ToTable("GuildWarBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.Opponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenaLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenaWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrandArenaLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrandArenaWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastKnownPower")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastKnownRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastKnownTeam")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitanArenaLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitanArenaWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId")
                        .IsUnique();

                    b.HasIndex("OpponentName");

                    b.ToTable("Opponents");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.PlayerSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenaCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Emeralds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrandArenaCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GrandArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildCoins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroExpPotions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamComposition")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamPower")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitanArenaCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TitanArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitanExpPotions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanTeam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("PlayerSnapshots");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.RaidBossAttack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("DamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rewards")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BossName");

                    b.HasIndex("Timestamp");

                    b.ToTable("RaidBossAttacks");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.SyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitanArenaBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentTitanTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("OurTitanTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("RankAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("Timestamp");

                    b.ToTable("TitanArenaBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestDrop", b =>
                {
                    b.HasOne("OrganizedJihad.Data.Models.ChestOpening", "ChestOpening")
                        .WithMany("Drops")
                        .HasForeignKey("ChestOpeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChestOpening");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestOpening", b =>
                {
                    b.Navigation("Drops");
                });
#pragma warning restore 612, 618
        }
    }
}
