// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizedJihad.Data;

#nullable disable

namespace OrganizedJihad.Data.Migrations
{
    [DbContext(typeof(GameDatabaseContext))]
    partial class GameDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("OrganizedJihad.Data.Models.AirshipGift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardSummaryText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "GiftId", "Timestamp");

                    b.ToTable("AirshipGifts");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ArenaBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("OurTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("RankAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("IsWin", "Timestamp");

                    b.ToTable("ArenaBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableReminders")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrencePattern")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReminderMinutesBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("IsCompleted");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChatActivitySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("MessagesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessagesSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SummaryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UniqueContacts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChatActivitySummaries");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOutgoing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageMetadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerLevel")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("SenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerMessageId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestOpeningId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChestOpeningId");

                    b.HasIndex("ItemId");

                    b.ToTable("ChestDrops");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestOpening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChestType");

                    b.HasIndex("Timestamp");

                    b.ToTable("ChestOpenings");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.DailyActivitySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenaBattlesFought")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignMissionsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DailyChestClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyQuestsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmeraldsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmeraldsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GoldEarned")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrandArenaBattlesFought")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildQuestsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutlandBossesFought")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SummaryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalActivityPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TowerFloorsCleared")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SummaryDate");

                    b.HasIndex("PlayerId", "SummaryDate")
                        .IsUnique();

                    b.ToTable("DailyActivitySummaries");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.DailyQuestCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QuestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestDate");

                    b.HasIndex("PlayerId", "QuestDate");

                    b.HasIndex("PlayerId", "QuestId", "CompletedAt");

                    b.ToTable("DailyQuestCompletions");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.EquipmentChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentItemId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroColorRank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialsConsumed")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("EquipmentChanges");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ExpeditionBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BossId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardData")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamComposition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpeditionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("ExpeditionBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("Type");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GrandArenaBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenseTeam")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentAttackTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpponentDefenseTeam")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("Timestamp");

                    b.ToTable("GrandArenaBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("GuildId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("GuildActivities");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildDungeonParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattlesFought")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DungeonDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DungeonId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DungeonType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighestStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTitanCharges")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Participated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitanChargesUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitaniteEarned")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildDungeonParticipations");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentContribution")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrandArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildRank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroRoster")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Prestige")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPower")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TitanArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanRoster")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalContribution")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VipLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildMemberSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Contribution")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildRank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Prestige")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamPower")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalContribution")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildMemberSnapshots");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildQuestCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("GuildActivityPoints")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QuestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestDate");

                    b.HasIndex("GuildId", "QuestDate");

                    b.HasIndex("PlayerId", "QuestDate");

                    b.ToTable("GuildQuestCompletions");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildRaidParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttacksMade")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BossDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BossLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GuildRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAttacks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MinionDamage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Participated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaidDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaidId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitaniteEarned")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GuildRaidParticipations");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildWarBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenderTeam")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnemyGuildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FortificationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OurTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WarId");

                    b.ToTable("GuildWarBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.GuildWarParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttacksMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefensePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FortsDefended")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAttacks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Participated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WarDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WarResult")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GuildWarParticipations");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtifactBook")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtifactRing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtifactWeapon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlyphData")
                        .HasColumnType("TEXT");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevel1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevel2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevel3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevel4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.HasIndex("HeroName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.HeroArtifactUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourcesConsumed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("HeroArtifactUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.HeroColorUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorNameAfter")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorNameBefore")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentConsumed")
                        .HasColumnType("TEXT");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("HeroColorUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.HeroGlyphUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("GlyphLevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlyphLevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlyphType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("HeroGlyphUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.HeroLevelUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("HeroLevelUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.HeroSkillUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillSlot")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("HeroSkillUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.HeroSkinUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNewUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkinId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkinStonesConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("HeroSkinUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.HeroStarUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoulStonesConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarsBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeroId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("HeroStarUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.InventoryItemUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetEntity")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsageContext")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ItemId", "Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("InventoryItemUsages");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.InventorySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalChests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalConsumables")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalEvolutionItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalHeroSoulStones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPetSoulStones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTitanSoulStones")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("InventorySnapshots");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.LoginReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVipBonus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardData")
                        .HasColumnType("TEXT");

                    b.Property<int>("StreakLength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ClaimedAt");

                    b.ToTable("LoginRewards");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.MailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MailId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawMailJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardSummaryText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("PlayerId", "MailId", "ReceivedAt");

                    b.ToTable("MailMessages");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.MailReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("MailId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "MailId", "RewardType", "RewardId", "Timestamp");

                    b.ToTable("MailRewards");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.MissionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("HighestLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHeroic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCompleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsHeroic");

                    b.HasIndex("MissionId");

                    b.HasIndex("PlayerId", "MissionId");

                    b.ToTable("MissionProgress");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.Opponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenaLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenaWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("GrandArenaLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrandArenaWins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastKnownPower")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastKnownRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastKnownTeam")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitanArenaLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitanArenaWins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLosses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId")
                        .IsUnique();

                    b.HasIndex("OpponentName");

                    b.ToTable("Opponents");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatronageData")
                        .HasColumnType("TEXT");

                    b.Property<long>("PetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("PetName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.PlayerSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArenaCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Emeralds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrandArenaCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GrandArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuildCoins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroExpPotions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamComposition")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamPower")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TitanArenaCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TitanArenaRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitanExpPotions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanTeam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("PlayerSnapshots");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.QuestCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardData")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("QuestType");

                    b.HasIndex("PlayerId", "CompletedAt");

                    b.ToTable("QuestCompletions");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.RaidBossAttack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttackTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("DamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rewards")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BossName");

                    b.HasIndex("Timestamp");

                    b.ToTable("RaidBossAttacks");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ResourceTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDetail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.HasIndex("ResourceType", "Source");

                    b.ToTable("ResourceTransactions");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ShopPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchasedAt");

                    b.HasIndex("ShopType");

                    b.HasIndex("PlayerId", "PurchasedAt");

                    b.ToTable("ShopPurchases");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.SyncMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SyncMetadata");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.Titan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactData")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Element")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkinLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SummonStars")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TitanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TitanId");

                    b.HasIndex("TitanName");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("Titans");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitanArenaBattle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OpponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpponentPower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpponentTitanTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("OurTitanTeam")
                        .HasColumnType("TEXT");

                    b.Property<int>("RankAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("Timestamp");

                    b.ToTable("TitanArenaBattles");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitanArtifactUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourcesConsumed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TitanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.HasIndex("TitanId", "Timestamp");

                    b.ToTable("TitanArtifactUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitanLevelUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("GoldSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PotionsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TitanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.HasIndex("TitanId", "Timestamp");

                    b.ToTable("TitanLevelUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitanSkillUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TitanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TitaniteSpent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.HasIndex("TitanId", "Timestamp");

                    b.ToTable("TitanSkillUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitanSkinUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNewUnlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelBefore")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkinId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkinStonesConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TitanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.HasIndex("TitanId", "Timestamp");

                    b.ToTable("TitanSkinUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitanStarUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoulStonesConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StarsBefore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TitanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.HasIndex("TitanId", "Timestamp");

                    b.ToTable("TitanStarUpgrades");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TitaniteTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BalanceAfter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseDescription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TitaniteTransactions");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.TowerProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorData")
                        .HasColumnType("TEXT");

                    b.Property<int>("HighestFloor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TowerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TowerType");

                    b.HasIndex("PlayerId", "TowerType");

                    b.ToTable("TowerProgress");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestDrop", b =>
                {
                    b.HasOne("OrganizedJihad.Data.Models.ChestOpening", "ChestOpening")
                        .WithMany("Drops")
                        .HasForeignKey("ChestOpeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChestOpening");
                });

            modelBuilder.Entity("OrganizedJihad.Data.Models.ChestOpening", b =>
                {
                    b.Navigation("Drops");
                });
#pragma warning restore 612, 618
        }
    }
}
